site_name: Aegir Hosting System
repo_url: https://github.com/aegir-project/documentation
theme: readthedocs
theme_dir: 'custom_theme'
site_favicon: '_images/favicon.ico'
extra_javascript:
  - '_js/menu.js'
extra_css:
  - '_css/toc.css'
  - '_css/menu.css'
  - '_css/images.css'
  - '_css/style.css'
pages:
- 'Home': 'index.md'
- 'Quick start': 'quick-start.md'
- 'Install': 'install.md'
- 'Install':
  - 'Upgrade': 'install/upgrade.md'
  - 'Uninstall': 'install/uninstall.md'
- 'Using Aegir': 'usage.md'
- 'Using Aegir':
  - 'Verifying servers, platforms and sites': 'usage/verify.md'
  - 'Sites': 'usage/sites.md'
  - 'Sites':
    - 'Site tasks': 'usage/sites/tasks.md'
    - 'Site aliases': 'usage/sites/aliases.md'
    - 'Importing sites': 'usage/sites/importing.md'
    - 'Exporting sites': 'usage/sites/exporting.md'
  - 'Platforms': 'usage/platforms.md'
  - 'Platforms':
    - 'Platform tasks': 'usage/platforms/tasks.md'
#  - 'Servers': 'usage/servers.md'
#  - 'Servers':
#    - 'Server tasks': 'usage/servers/tasks.md'
  - 'Advanced features': 'usage/advanced.md'
  - 'Advanced features':
    - 'SSL': 'usage/advanced/ssl.md'
    - 'Multiple servers': 'usage/advanced/remote-servers.md'
    - 'Access control': 'usage/advanced/clients.md'
    - 'ProvisionACL': 'usage/advanced/provisionacl.md'
- 'Extending Aegir': 'extend.md'
- 'Extending Aegir':
  - 'Frontend': 'extend/frontend.md'
  - 'Backend': 'extend/backend.md'
  - 'Altering behaviours': 'extend/altering-behaviours.md'
  - 'Contributed projects': 'extend/contrib.md'
- 'Developing Aegir': 'develop.md'
- 'Developing Aegir':
  - 'Design and terminology': 'develop/terminology.md'
  - 'Architecture': 'develop/architecture.md'
  - 'Provision': 'develop/provision.md'
  - 'Provision':
    - 'Contexts': 'develop/provision/contexts.md'
  - 'Projects repositories': 'develop/repositories.md'
  - 'Release process': 'community/release-process.md'
  - 'Release process':
    - 'community/release-process/debian-packaging.md'
- 'Help': 'help/contact.md'
- 'Community': 'community.md'
- 'Community':
  - 'Code of Conduct': 'community/code-of-conduct.md'
  - 'Core team': 'community/core-team.md'
  - 'Core team':
    - 'Criteria': 'community/core-team/criteria.md'
    - 'Leadership': 'community/core-team/leadership.md'
    - 'Welcoming a new member': 'community/core-team/welcome.md'
  - 'Resources': 'community/resources.md'
  - 'Service providers': 'community/services.md'
- 'Release notes': 'release-notes/3.10.md'
- 'Release notes':
  - '3.0': 'release-notes/3.0.md'
  - '3.1': 'release-notes/3.1.md'
  - '3.2': 'release-notes/3.2.md'
  - '3.3': 'release-notes/3.3.md'
  - '3.4': 'release-notes/3.4.md'
  - '3.5': 'release-notes/3.5.md'
  - '3.6': 'release-notes/3.6.md'
  - '3.7': 'release-notes/3.7.md'
  - '3.8': 'release-notes/3.8.md'
  - '3.9': 'release-notes/3.9.md'
  - '3.10': 'release-notes/3.10.md'
